reference doc commented out because of
Process is terminated due to StackOverflowException.
Running build failed.
Error:
System.Exception: generating reference documentation failed
   at FSI_0001.Build.clo@192-24.Invoke(Unit _arg12) in C:\projects\projectscaffold-8rxjr\build.fsx:line 194
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 483

---------------------------------------------------------------------